# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from bugtriage_mcp.v1 import triage_pb2 as bugtriage__mcp_dot_v1_dot_triage__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bugtriage_mcp/v1/triage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BugTriageStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TriageBug = channel.unary_unary(
                '/bugtriage_mcp.v1.BugTriage/TriageBug',
                request_serializer=bugtriage__mcp_dot_v1_dot_triage__pb2.TriageBugRequest.SerializeToString,
                response_deserializer=bugtriage__mcp_dot_v1_dot_triage__pb2.TriageBugResponse.FromString,
                _registered_method=True)
        self.FindSimilarBugs = channel.unary_unary(
                '/bugtriage_mcp.v1.BugTriage/FindSimilarBugs',
                request_serializer=bugtriage__mcp_dot_v1_dot_triage__pb2.FindSimilarBugsRequest.SerializeToString,
                response_deserializer=bugtriage__mcp_dot_v1_dot_triage__pb2.FindSimilarBugsResponse.FromString,
                _registered_method=True)
        self.GetBug = channel.unary_unary(
                '/bugtriage_mcp.v1.BugTriage/GetBug',
                request_serializer=bugtriage__mcp_dot_v1_dot_triage__pb2.GetBugRequest.SerializeToString,
                response_deserializer=bugtriage__mcp_dot_v1_dot_triage__pb2.Bug.FromString,
                _registered_method=True)
        self.SearchLogs = channel.unary_unary(
                '/bugtriage_mcp.v1.BugTriage/SearchLogs',
                request_serializer=bugtriage__mcp_dot_v1_dot_triage__pb2.SearchLogsRequest.SerializeToString,
                response_deserializer=bugtriage__mcp_dot_v1_dot_triage__pb2.SearchLogsResponse.FromString,
                _registered_method=True)


class BugTriageServicer:
    """Missing associated documentation comment in .proto file."""

    def TriageBug(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindSimilarBugs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBug(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BugTriageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TriageBug': grpc.unary_unary_rpc_method_handler(
                    servicer.TriageBug,
                    request_deserializer=bugtriage__mcp_dot_v1_dot_triage__pb2.TriageBugRequest.FromString,
                    response_serializer=bugtriage__mcp_dot_v1_dot_triage__pb2.TriageBugResponse.SerializeToString,
            ),
            'FindSimilarBugs': grpc.unary_unary_rpc_method_handler(
                    servicer.FindSimilarBugs,
                    request_deserializer=bugtriage__mcp_dot_v1_dot_triage__pb2.FindSimilarBugsRequest.FromString,
                    response_serializer=bugtriage__mcp_dot_v1_dot_triage__pb2.FindSimilarBugsResponse.SerializeToString,
            ),
            'GetBug': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBug,
                    request_deserializer=bugtriage__mcp_dot_v1_dot_triage__pb2.GetBugRequest.FromString,
                    response_serializer=bugtriage__mcp_dot_v1_dot_triage__pb2.Bug.SerializeToString,
            ),
            'SearchLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchLogs,
                    request_deserializer=bugtriage__mcp_dot_v1_dot_triage__pb2.SearchLogsRequest.FromString,
                    response_serializer=bugtriage__mcp_dot_v1_dot_triage__pb2.SearchLogsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bugtriage_mcp.v1.BugTriage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bugtriage_mcp.v1.BugTriage', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BugTriage:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TriageBug(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bugtriage_mcp.v1.BugTriage/TriageBug',
            bugtriage__mcp_dot_v1_dot_triage__pb2.TriageBugRequest.SerializeToString,
            bugtriage__mcp_dot_v1_dot_triage__pb2.TriageBugResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindSimilarBugs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bugtriage_mcp.v1.BugTriage/FindSimilarBugs',
            bugtriage__mcp_dot_v1_dot_triage__pb2.FindSimilarBugsRequest.SerializeToString,
            bugtriage__mcp_dot_v1_dot_triage__pb2.FindSimilarBugsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBug(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bugtriage_mcp.v1.BugTriage/GetBug',
            bugtriage__mcp_dot_v1_dot_triage__pb2.GetBugRequest.SerializeToString,
            bugtriage__mcp_dot_v1_dot_triage__pb2.Bug.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bugtriage_mcp.v1.BugTriage/SearchLogs',
            bugtriage__mcp_dot_v1_dot_triage__pb2.SearchLogsRequest.SerializeToString,
            bugtriage__mcp_dot_v1_dot_triage__pb2.SearchLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
